// This file is only for static constants that rarely change.

export const ASSESSMENT_TYPES = [
  "Unknown",
  "Exam 1",
  "Exam 2",
  "Exam 3",
  "Midterm",
  "Final",
  "Quiz 1",
  "Quiz 2",
  "Quiz 3",
  "Quiz 4",
  "Quiz 5",
  "Quiz 6",
  "Quiz 7",
  "Quiz 8",
  "Quiz 9",
  "Quiz 10",
  "Lab 1",
  "Lab 2",
  "Lab 3",
  "Lab 4",
  "Lab 5",
  "Lab 6",
  "Lab 7",
  "Lab 8",
  "Lab 9",
  "Lab 10",
  "Homework 1",
  "Homework 2",
  "Homework 3",
  "Homework 4",
  "Homework 5",
  "Homework 6",
  "Homework 7",
  "Homework 8",
  "Homework 9",
  "Homework 10",
  "Backwork",
  "Unknown",
];

export const VERSIONS = ["Key", "Blank", "Student"];

export const SEMESTERS = ["Fall", "Spring", "Summer", "Unknown"];
